# Generated by Django 6.0.3 on 2026-03-09 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('fono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('tecnico', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia_estado', models.CharField(blank=True, max_length=150, null=True)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('valor_pago_tecnico', models.IntegerField(blank=True, null=True)),
                ('tiempo_trabajo_total', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta_contable', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_incidencias_dia', models.IntegerField(default=0)),
                ('estado_pago', models.CharField(choices=[('aprobado', 'Aprobado'), ('revision', 'En Revisión'), ('rechazado', 'Rechazado')], default='aprobado', max_length=20)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='servicios.cargamensual')),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='servicios.contratista')),
            ],
        ),
    ]
