# Generated by Django 6.0.3 on 2026-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='valor_pago_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
