# Generated by Django 6.0.3 on 2026-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_serviciotecnico_valor_pago_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamensual',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamensual',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
