# Generated by Django 6.0.3 on 2026-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_cargamensual_anio_cargamensual_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaB2B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('kam', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
