# Generated by Django 6.0.3 on 2026-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_cuentab2b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentab2b',
            name='fecha_creacion',
        ),
    ]
