# Generated by Django 6.0.3 on 2026-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_cuentab2b_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentab2b',
            name='cuenta',
            field=models.CharField(max_length=50),
        ),
    ]
