# Generated by Django 6.0.3 on 2026-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_cuentab2b_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CECO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50)),
                ('ceco', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'unique_together': {('cuenta', 'ceco')},
            },
        ),
    ]
