# Generated by Django 6.0.3 on 2026-03-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_ceco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('interno', 'Técnico Interno'), ('contratista', 'Técnico Contratista')], default='interno', max_length=20)),
                ('categoria', models.CharField(choices=[('principal', 'Principal'), ('remoto', 'Remoto')], default='remoto', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='servicios.contratista')),
            ],
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='tecnico_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='servicios.tecnico'),
        ),
    ]
