# Generated by Django 6.0.3 on 2026-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_tecnico_serviciotecnico_tecnico_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='es_b2b',
            field=models.BooleanField(default=False),
        ),
    ]
