# Generated by Django 6.0.3 on 2026-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_serviciotecnico_es_b2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='cuenta',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='servicio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
