# Generated by Django 6.0.3 on 2026-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_serviciotecnico_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='numero_incidencias_60_dias',
            field=models.IntegerField(default=0),
        ),
    ]
