# Generated by Django 6.0.3 on 2026-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_serviciotecnico_numero_incidencias_60_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciotecnico',
            name='estado_pago',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('revision', 'En Revisión'), ('rechazado', 'Rechazado'), ('no_cobrado', 'No Cobrado')], default='aprobado', max_length=20),
        ),
    ]
