# Generated by Django 6.0.3 on 2026-04-19 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_alter_serviciotecnico_estado_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('alias_normalizado', models.CharField(db_index=True, max_length=200, unique=True)),
                ('creado_en_revision', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='AliasTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('alias_normalizado', models.CharField(db_index=True, max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('hash_archivo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('cargado', 'Cargado'), ('procesando', 'Procesando'), ('procesado', 'Procesado'), ('procesado_con_observaciones', 'Procesado con observaciones'), ('error', 'Error')], default='cargado', max_length=40)),
                ('total_filas', models.IntegerField(default=0)),
                ('filas_procesadas', models.IntegerField(default=0)),
                ('filas_publicadas', models.IntegerField(default=0)),
                ('filas_con_observacion', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('contratista_ambiguo', 'Contratista ambiguo'), ('contratista_no_encontrado', 'Contratista no encontrado'), ('tecnico_sin_match', 'Técnico sin match'), ('tecnico_ambiguo', 'Técnico ambiguo'), ('cuenta_invalida', 'Cuenta inválida'), ('ceco_no_encontrado', 'CECO no encontrado'), ('fecha_invalida', 'Fecha inválida'), ('monto_invalido', 'Monto inválido'), ('dato_incompleto', 'Dato incompleto'), ('duplicado', 'Duplicado'), ('otro', 'Otro')], max_length=50)),
                ('detalle', models.TextField()),
                ('valor_detectado', models.CharField(blank=True, max_length=255, null=True)),
                ('sugerencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='pendiente', max_length=20)),
                ('resuelto_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['estado', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioTecnicoRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fila_numero', models.IntegerField()),
                ('data', models.JSONField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('publicado', 'Publicado'), ('error', 'Error'), ('revision', 'Revisión')], default='pendiente', max_length=20)),
                ('procesado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('numero_ot', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tecnico_texto', models.CharField(blank=True, max_length=200, null=True)),
                ('tecnico_normalizado', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('cuenta_texto', models.CharField(blank=True, max_length=400, null=True)),
                ('cuenta_contable', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('valor_pago_original_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_pago_tecnico', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['archivo_carga', 'fila_numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='cargamensual',
            options={'ordering': ['-anio', '-mes', '-id']},
        ),
        migrations.AlterModelOptions(
            name='ceco',
            options={'ordering': ['cuenta', 'ceco']},
        ),
        migrations.AlterModelOptions(
            name='contratista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cuentab2b',
            options={'ordering': ['cuenta']},
        ),
        migrations.AlterModelOptions(
            name='serviciotecnico',
            options={'ordering': ['-fecha_finalizacion', '-id']},
        ),
        migrations.AlterModelOptions(
            name='tecnico',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='cargamensual',
            old_name='fecha_carga',
            new_name='fecha_creacion',
        ),
        migrations.AlterUniqueTogether(
            name='ceco',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargamensual',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cargamensual',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ceco',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ceco',
            name='cuenta_normalizada',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ceco',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ceco',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratista',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='empresa_normalizada',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contratista',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='nombre_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='contratista',
            name='observacion_revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='origen',
            field=models.CharField(choices=[('json', 'JSON'), ('excel', 'Excel'), ('manual', 'Manual'), ('revision', 'Creado en revisión')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='contratista',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratista',
            name='rut_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cuentab2b',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentab2b',
            name='cuenta_normalizada',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentab2b',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentab2b',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='ceco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='servicios.ceco'),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='fecha_creacion_origen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='nombre_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='requiere_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuentab2b',
            name='cuenta',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='cuenta_contable',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciotecnico',
            name='numero',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ceco',
            unique_together={('cuenta_normalizada', 'ceco')},
        ),
        migrations.AddIndex(
            model_name='contratista',
            index=models.Index(fields=['nombre_normalizado'], name='servicios_c_nombre__48b8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contratista',
            index=models.Index(fields=['empresa_normalizada'], name='servicios_c_empresa_6a5203_idx'),
        ),
        migrations.AddIndex(
            model_name='contratista',
            index=models.Index(fields=['rut_normalizado'], name='servicios_c_rut_nor_c56e22_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratista',
            constraint=models.UniqueConstraint(condition=models.Q(('rut_normalizado', ''), _negated=True), fields=('rut_normalizado',), name='uq_contratista_rut_normalizado_no_vacio'),
        ),
        migrations.AddField(
            model_name='aliascontratista',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='servicios.contratista'),
        ),
        migrations.AddField(
            model_name='aliastecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='servicios.tecnico'),
        ),
        migrations.AddField(
            model_name='archivocarga',
            name='carga_mensual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='servicios.cargamensual'),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='archivo_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_publicados', to='servicios.archivocarga'),
        ),
        migrations.AddField(
            model_name='serviciotecnicoraw',
            name='archivo_carga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_raw', to='servicios.archivocarga'),
        ),
        migrations.AddField(
            model_name='observacionimportacion',
            name='raw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='servicios.serviciotecnicoraw'),
        ),
        migrations.AddField(
            model_name='serviciotecnico',
            name='raw',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_publicado', to='servicios.serviciotecnicoraw'),
        ),
        migrations.AddIndex(
            model_name='serviciotecnico',
            index=models.Index(fields=['numero'], name='servicios_s_numero_69dba8_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciotecnico',
            index=models.Index(fields=['cuenta_contable'], name='servicios_s_cuenta__cc11bf_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciotecnico',
            index=models.Index(fields=['estado_pago'], name='servicios_s_estado__6d6089_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciotecnico',
            index=models.Index(fields=['tipo_servicio'], name='servicios_s_tipo_se_ded157_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciotecnico',
            index=models.Index(fields=['fecha_finalizacion'], name='servicios_s_fecha_f_a95773_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviciotecnico',
            constraint=models.UniqueConstraint(condition=models.Q(('raw', None), _negated=True), fields=('raw',), name='uq_servicio_raw_unico'),
        ),
        migrations.AlterUniqueTogether(
            name='serviciotecnicoraw',
            unique_together={('archivo_carga', 'fila_numero')},
        ),
    ]
