# Generated by Django 6.0.3 on 2026-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_aliascontratista_aliastecnico_archivocarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciotecnico',
            name='informe_tecnico',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('no_aplica', 'No aplica')], default=None, max_length=20, null=True),
        ),
    ]
